name: Daily LeetCode Report Update

on:
  schedule:
    # Run every hour from 9:05 AM to 12:05 AM (next day)
    - cron: '59 16-23,0-6 0 * * *'
  workflow_dispatch:  # Allow manual triggering

# Add permissions at the job level
permissions:
  contents: write

jobs:
  update_report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Use the built-in token with proper permissions
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install tabulate requests; fi
          
      - name: Run LeetCode tracker
        run: |
          python leetcode_tracker.py
          
      - name: Generate web report
        run: |
          python generate_web_report.py
          
      - name: Commit updated report data
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add report_data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update report data [skip ci]"
          git push
